### ISSUE TITLE
[SCALE] Performance Tuning

### ISSUE THREAD

**Issue by djivey** [GeorgiaCyber/kinetic#125]
Tune rabbitmq, mariadb, haproxy and memcached to support a higher rate of API saturation. 

I am using this yaml in rally to test API rates.

```
{% set flavor_name = flavor_name or "mem.nano" %}
---
  NovaServers.boot_server:
    -
      args:
        flavor:
            name: "{{ flavor_name }}"
        image:
            name: "^cirros"
      runner:
        type: "rps"
        times: 1000
        rps: 2
      context:
        users:
          tenants: 10
          users_per_tenant: 2
        quotas:
          nova:
            instances: -1
            cores: -1
            ram: -1 
          neutron:
            port: -1
      sla:
        failure_rate:
          max: 1
```

initial tests hat a failure rate with a success rate of about 42%. The goal is to get to 100% success rate.
