### ISSUE TITLE
Ceph Pool Creation

### ISSUE THREAD

**Issue by bitskri3g** [GeorgiaCyber/kinetic#5]
Currently, there is no good place to create the three required pools

```ceph osd pool create vms```
```ceph osd pool create images```
```ceph osd pool create volumes```

and then ```rbd pool init {{ pool }}``` as a follow-on.

You can't do it during the cephmon phase because there aren't enough OSDs to justify the quantity of PGs.  The requiring services (glance, etc.) don't have access to client.admin, and I'd rather not give it to them.

Needs a solution; for now pools are created manually as a final step prior to deploying openstack.

**Comment by bitskri3g** [comment]
Changed course here.  Fixed by 6bb3f7cbd2e269caab5263747b03125cde3689f5 among others.

For each service that needs a pool, it will:

fire an event that says how many PGs the pool should have:
```

make_images_pool:
  event.send:
    - name: create/{{ grains['type'] }}/pool
    - data: 
pgs: {{ pillar['cephconf']['images_pgs'] }}
```

The reactor should then pull out the number of pgs, and then have the ceph monitor with spawning:0 create the pool on behalf of the requesting service:

```
create_glance_pool:
  local.cmd.run:
    - tgt: 'G@spawning:0 and G@type:cephmon'
    - tgt_type: compound
    - arg:
- ceph osd pool create images {{ data ['data']['pgs'] }}
```

This has been tested and is working for glance, nova, and cinder.  Swift was unaffected by this issue.
