### ISSUE TITLE
[BUG] Orchestration does not retry hung physical endpoints

### ISSUE THREAD

**Issue by bitskri3g** [GeorgiaCyber/kinetic#89]
Currently, the orchestration system does not proceed from step-to-step until *all* endpoints that it expects complete the requisite task.  So, when transient errors break a bare-metal installation (networking, installer issues, etc.), all endpoints will fail rather than just that one.  Manually running an orch.generate fixes it, but the user shouldn't have to do this in an ideal world, particularly since running and out-of-band orch.generate won't make orch.init report success, even though it will still technically be fully functional.

Things that have to be done:

- [ ] Identify endpoint(s) that failed after a certain timeout - this will get tricky during installation routines since there are only a handful of places where affirmation checks can be done, but it should be doable.
- [ ] Re-try the failed routine on these endpoints *without* halting the progress of others of the same type
- [ ] Ensure that orch.init doesn't exit nonzero if the retry(ies) are successful

There are things like onfail, etc present in the state system, but I'm not sure if these are granular enough to handle retries in this manner.

**Comment by bitskri3g** [comment]
Ok after doing a little bit of reading it sounds like that this functionality should be entirely pushed off to pxe and handled internally, kind of like how controllers use the virtual_prep and virtual_zero states.

It could go something like this:

zeroize.sls
```
...
{% for id in targets %}
init_host_{{ id }}:
  salt.state:
    - tgt: pxe
    - sls:
      - orch/states/init_physical
    - pillar:
        tgt: {{ targets[id]['api_host'] }}
        api_user: {{ api_user }}
        api_pass: {{ api_pass }}
    - concurrent: True
    - retry:
        interval: 10
        attempts: 3
{% endfor %}

... (remove wheel, expire host addresses, etc. no follow-on changes)
```

init_physical.sls
```
## this is pseudocode, but you get the idea
set_bootonce_{{ host }}:
  module.run:
    - name: redfish.set_bootonce
    - args: some args

resset_host_{{ host }}:
  module.run:
    - name: redfish.reset_host
    - args: some args

assign_uuid_to_{{ id }}:
  module.run:
    - name: file.write
    - args: some args

loop_until_eval_pre:
  loop.until:
    - name: get signal from pre
    - failhard: True
## https://docs.fedoraproject.org/en-US/fedora/rawhide/install-guide/appendixes/Kickstart_Syntax_Reference/#sect-kickstart-preinstall
## https://www.debian.org/releases/buster/amd64/apbs05.en.html early command

loop_until_eval_post:
  loop.until:
    - name: get signal from post
    - failhard: True
## https://docs.fedoraproject.org/en-US/fedora/rawhide/install-guide/appendixes/Kickstart_Syntax_Reference/#sect-kickstart-postinstall
## https://www.debian.org/releases/buster/amd64/apbs05.en.html late command
```

Using these mechanisms, I believe that the orchestration runner should successfully execute retries (including resetting individual hosts) and complete successfully (assuming that the 3d time is the charm...).  Non-transient errors will still present themselves.
